### ISSUE TITLE
期望有个更简洁的 vbase 选项

### ISSUE THREAD

**Issue by Chanzhaoyu** [x-wink/wink-snippets#1]
非常感谢你的 `wink-snippets` 插件，是我在 `vscode` 上用的最顺手的 `Vue3` 代码提示插件。

请问可以将 `vbase` 模版的代码块更精简点吗，如下：

```vue
<template>
  <div></div>
</template>

<script setup lang="ts">

</script>

<style scoped>

</style>
```

因为目前大多数项目基本都是结合 `tailwindcss` 或 `unocss`  等  `css` 框架使用，每个模版定义元素 `class` 和 `style` 应该已是少数。综上，我每次 `vbase` 都需要删除 3 个 `container` 内容，所以我还保留着 `vue3-snippets-for-vscode` 这个插件来生成初始模版。 我觉得精简掉的模版就能满足大部分的要求，当然这是我个人的想法，也许每个人的需求不一样。

再次感谢你的贡献

**Comment by x-wink** [comment]
感谢你的认可和支持，我也觉得应该弄一个精简版和一些特殊的版本适应不同使用场景和需求，我自己有时候用也要删掉container

**Comment by x-wink** [comment]
已发布v1.0.5

**Comment by Chanzhaoyu** [comment]
> 已发布v1.0.5

Thank you again
